
      <div class="documentwrapper">
          <div class="body">
            
  <p>Setting up a local development environment</p>
<p>We&#8217;re going to assume where your Website is located on your machine. If you&#8217;re on OSX using MAMP, it&#8217;s likely to be:</p>
<p>MAMP:</p>
<p>/Applications/MAMP/htdocs</p>
<p>You can verify this by returning to the MAMP preferences panel:
<a class="reference external" href="http://www.lullabot.com/videos/install-local-web-server-mac-osx">http://www.lullabot.com/videos/install-local-web-server-mac-osx</a></p>
<p># Click Apache
# Look at the value in the Document Root</p>
<p>WAMP</p>
<p>Windows</p>
<p>If you&#8217;re running Windows and WAMP, it&#8217;s likely to be:</p>
<p><a class="reference external" href="http://www.lullabot.com/videos/install-local-web-server-mac-osx">http://www.lullabot.com/videos/install-local-web-server-mac-osx</a></p>


          </div>
      </div>
      